### ISSUE TITLE
Implement a Parview .vtk export function from the ResultsReader

### ISSUE THREAD

**Issue by drlukeparry** [drlukeparry/pyccx#1]
A paraview .vtk export option to view the results from Calculix would be useful to post-process the results and provide a better presentation of the results. 

It is possible to visualise the results using Matplotlib, however, the performance is inadaquate for large mesh sizes

Update: The exported .frd files will be transformed within the ResultsProcessor and a separator exporter translator method will become available for conversion to Paraview .vtu format

Update 2: An additional function has been created to export the .pvd XML file that are used for exporting the complete timestep / increment history generated from Calculix.

**Comment by FranseFrikandel** [comment]
Appears a Python implementation for this already exists:
https://github.com/calculix/ccx2paraview

Should be fairly easy to implement this into the ResultsReader from here.

**Comment by drlukeparry** [comment]
Yes, an initial function has been created in the _dev_ branch and writes the XML output internally - to avoid the dependency of vtk (this does not install on Mac easily). This reuses the .frd option internally in the ResultsReader for parsing the results.

I have not yet separated functionality to export the full load-step increments, but that should be straightforward to include.

Unfortunately, there isn't a straightforward way to map integration/quadrature points into the .vtu format. Average quantities at the centroid can be specified per element cell, otherwise this will need further work to incorporate.
